base_url = "https://ansorum.com/"
title = "Ansorum"
description = "An answer-first compiler for agent-readable and human-readable knowledge."

compile_sass = true
build_search_index = true

taxonomies = [
  { name = "theme-tags"}
]

[search]
index_format = "elasticlunr_json"

[markdown]
external_links_class = "external"

[markdown.highlighting]
theme = "catppuccin-mocha"
#error_on_missing_language = true

[link_checker]
internal_level = "warn"

[extra]
author = "Vincent Prouillet"
